name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: cd client && npm ci --legacy-peer-deps
    - name: Install Playwright Browsers
      run: cd client && npx playwright install --with-deps
    - name: Run Playwright tests
      run: cd client && npm run test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: client/playwright-report/
        retention-days: 30